apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: nginx-server
          image: nginx:alpine
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: web-service # this is the internal DNS name
spec:
  type: ClusterIP # visible just inside the cluster
  selector:
    app: web-app # sends traffic to pods with this label
  ports:
    - protocol: TCP
      port: 80 # port that the service listens on
      targetPort: 80 # port of the container inside the pod
