name: python-syntax-check-linter

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cclauss/Find-Python-syntax-errors-action@master
      - uses: sunnysid3up/python-linter@master
        with:
          source: "Learning/Docker/Docker/Containerization/http-monitor"
          mypy-options: "--ignore-missing-imports --show-error-codes"
          isort-options: "-w 100"
          django: false
          
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t monitor-app:latest -f Learning/Docker/Docker/Containerization/http-monitor/dockerfile Learning/Docker/Docker/Containerization/http-monitor
      
    
